name: Deploy Production

on: workflow_dispatch

jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: test
        run: mkdir dist && cd dist && sh ../run.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
